### ISSUE TITLE
data.user contains the Slack ID, not the user's name

### ISSUE THREAD

**Issue by snex** [dblock/slack-ruby-bot#52]
example code:
``` 
  command 'start' do |client, data, match|
      client.say(text: "hi #{data.user}, a new game started. have players set their amounts.", channel: data.channel)
      @game = Game.new
    end 
  end
```

The output in the chat looks like the following:

"hi U0Q7SU64S, a new game started. have players set their amounts."

Ruby 2.3.0
slack-ruby-bot 0.6.2

**Comment by dblock** [comment]
That's by design in the Slack RealTime API. If you want the username, you'll have to look it up. There're two ways to do this, a looking up the local store, via `client.users` or a web API call via `users_info`. If you want to just render it on the client without looking it up, mark it up: `<@#{data.user}>` and it will render as the username.
