### ISSUE TITLE
How to perform actions on a schedule?

### ISSUE THREAD

**Issue by mdub** [dblock/slack-ruby-bot#72]
I'd like my bot to perform an action at 9:00 every weekday.  Is there an easy way to do that?

**Comment by accessd** [comment]
I suppose you can use Command-Line Client from https://github.com/dblock/slack-ruby-client, that will be launched by cron.

**Comment by dblock** [comment]
I would use a ruby scheduler like https://github.com/jmettraux/rufus-scheduler or a plain timer, like https://github.com/celluloid/timers if you use Celluloid-io and want a periodic operation rather than one at a certain time.

I don't think we want slack-ruby-bot to have a schedule DSL, that's not very slack specific, so I am going to close this one for now.
